language: node_js
node_js:
  - "14"
cache: yarn
before_install:
  - npm i -g yarn@2.0.0-rc.27
  - yarn set version berry
install:
  - yarn install --immutable
script:
  - yarn run build:ci
after_success:
  - yarn run coverage
