name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm i -g yarn@berry
    - run: yarn set version berry
    - run: yarn set version 2.1.1
    - run: yarn install --immutable
    - run: yarn test
    - run: yarn build
      env:
        CI: true
